package model;

import java.io.Serializable;

/**
 * FeedSapEmployee definition.
 * 
 * This file was generated by Ignite Web Console (01/10/2019, 03:32)
 **/
public class FeedSapEmployee implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for sevendigitstaffid. */
    private Long sevendigitstaffid;

    /** Value for forename. */
    private String forename;

    /** Value for surname. */
    private String surname;

    /** Value for sapcostcentrecompany. */
    private String sapcostcentrecompany;

    /** Value for startdt. */
    private String startdt;

    /** Value for enddt. */
    private String enddt;

    /** Value for corporatetitle. */
    private String corporatetitle;

    /** Value for globallevel. */
    private String globallevel;

    /** Value for stafftype. */
    private String stafftype;

    /** Value for staffsubtype. */
    private String staffsubtype;

    /** Value for staffstatus. */
    private String staffstatus;

    /** Value for staffclass. */
    private String staffclass;

    /** Value for globalstaffid. */
    private Long globalstaffid;

    /** Value for taxnumber. */
    private String taxnumber;

    /** Value for orgunit. */
    private String orgunit;

    /** Value for orgunitabbv. */
    private String orgunitabbv;

    /** Value for orgunitdesc. */
    private String orgunitdesc;

    /** Value for dept. */
    private String dept;

    /** Value for deptabbv. */
    private String deptabbv;

    /** Value for deptdesc. */
    private String deptdesc;

    /** Value for buildingdesc. */
    private String buildingdesc;

    /** Value for countrydesc. */
    private String countrydesc;

    /** Value for firstname. */
    private String firstname;

    /** Value for jobkey. */
    private String jobkey;

    /** Value for linemanagerid. */
    private String linemanagerid;

    /** Value for previouslastname. */
    private String previouslastname;

    /** Value for gender. */
    private String gender;

    /** Value for lastdayworked. */
    private String lastdayworked;

    /** Value for emailaddr. */
    private String emailaddr;

    /** Value for previouscostcentre. */
    private String previouscostcentre;

    /** Value for lastdaypaid. */
    private String lastdaypaid;

    /** Value for dateofbirth. */
    private String dateofbirth;

    /** Value for nationalitycode. */
    private String nationalitycode;

    /** Value for maternitydatefrom. */
    private String maternitydatefrom;

    /** Value for maternitydateto. */
    private String maternitydateto;

    /** Value for absence. */
    private String absence;

    /** Value for entitycode. */
    private String entitycode;

    /** Value for entitytext. */
    private String entitytext;

    /** Value for busarea1. */
    private String busarea1;

    /** Value for busareaabbr1. */
    private String busareaabbr1;

    /** Value for busareadesc1. */
    private String busareadesc1;

    /** Value for busarea2. */
    private String busarea2;

    /** Value for busareaabbr2. */
    private String busareaabbr2;

    /** Value for busareadesc2. */
    private String busareadesc2;

    /** Value for busarea3. */
    private String busarea3;

    /** Value for busareaabbr3. */
    private String busareaabbr3;

    /** Value for busareadesc3. */
    private String busareadesc3;

    /** Value for busarea4. */
    private String busarea4;

    /** Value for busareaabbr4. */
    private String busareaabbr4;

    /** Value for busareadesc4. */
    private String busareadesc4;

    /** Value for leavingcode. */
    private String leavingcode;

    /** Value for graduatestartdate. */
    private String graduatestartdate;

    /** Value for localhirerehire. */
    private String localhirerehire;

    /** Value for localsupervisor. */
    private String localsupervisor;

    /** Value for linemanagerbrid. */
    private String linemanagerbrid;

    /** Value for brid. */
    private String brid;

    /** Value for personnelarea. */
    private String personnelarea;

    /** Value for personnelareadesc. */
    private String personnelareadesc;

    /** Value for busarea5. */
    private String busarea5;

    /** Value for busareaabbr5. */
    private String busareaabbr5;

    /** Value for busareadesc5. */
    private String busareadesc5;

    /** Value for subfunction. */
    private String subfunction;

    /** Value for subfunctiondesc. */
    private String subfunctiondesc;

    /** Value for function. */
    private String function;

    /** Value for functiondesc. */
    private String functiondesc;

    /** Value for sapcostcentretext. */
    private String sapcostcentretext;

    /** Value for companycode. */
    private String companycode;

    /** Value for companycodetxt. */
    private String companycodetxt;

    /** Value for operationalstatusind. */
    private String operationalstatusind;

    /** Value for citizencard. */
    private String citizencard;

    /** Value for evetelephoneno. */
    private String evetelephoneno;

    /** Value for identificationcard. */
    private String identificationcard;

    /** Value for pannumber. */
    private String pannumber;

    /** Value for nationalidcardno. */
    private String nationalidcardno;

    /** Value for labourcardnumberid. */
    private String labourcardnumberid;

    /** Value for personalmobceltelephoneno. */
    private String personalmobceltelephoneno;

    /** Value for employmentpass. */
    private String employmentpass;

    /** Value for singaporeblue. */
    private String singaporeblue;

    /** Value for passport. */
    private String passport;

    /** Value for hongkongidentityno. */
    private String hongkongidentityno;

    /** Value for uniquenationalid. */
    private String uniquenationalid;

    /** Value for singaporepink. */
    private String singaporepink;

    /** Value for visaworkpermitreftier2. */
    private String visaworkpermitreftier2;

    /** Value for busarea6. */
    private String busarea6;

    /** Value for busareaabbr6. */
    private String busareaabbr6;

    /** Value for busareadesc6. */
    private String busareadesc6;

    /** Value for busarea7. */
    private String busarea7;

    /** Value for busareaabbr7. */
    private String busareaabbr7;

    /** Value for busareadesc7. */
    private String busareadesc7;

    /** Value for busarea8. */
    private String busarea8;

    /** Value for busareaabbr8. */
    private String busareaabbr8;

    /** Value for busareadesc8. */
    private String busareadesc8;

    /** Value for busarea9. */
    private String busarea9;

    /** Value for busareaabbr9. */
    private String busareaabbr9;

    /** Value for busareadesc9. */
    private String busareadesc9;

    /** Value for busarea10. */
    private String busarea10;

    /** Value for busareaabbr10. */
    private String busareaabbr10;

    /** Value for busareadesc10. */
    private String busareadesc10;

    /** Value for opnonopstatusreason. */
    private String opnonopstatusreason;

    /** Value for opnonopstartdate. */
    private String opnonopstartdate;

    /** Value for opnonopenddate. */
    private String opnonopenddate;

    /** Empty constructor. **/
    public FeedSapEmployee() {
        // No-op.
    }

    /** Full constructor. **/
    public FeedSapEmployee(Long sevendigitstaffid,
        String forename,
        String surname,
        String sapcostcentrecompany,
        String startdt,
        String enddt,
        String corporatetitle,
        String globallevel,
        String stafftype,
        String staffsubtype,
        String staffstatus,
        String staffclass,
        Long globalstaffid,
        String taxnumber,
        String orgunit,
        String orgunitabbv,
        String orgunitdesc,
        String dept,
        String deptabbv,
        String deptdesc,
        String buildingdesc,
        String countrydesc,
        String firstname,
        String jobkey,
        String linemanagerid,
        String previouslastname,
        String gender,
        String lastdayworked,
        String emailaddr,
        String previouscostcentre,
        String lastdaypaid,
        String dateofbirth,
        String nationalitycode,
        String maternitydatefrom,
        String maternitydateto,
        String absence,
        String entitycode,
        String entitytext,
        String busarea1,
        String busareaabbr1,
        String busareadesc1,
        String busarea2,
        String busareaabbr2,
        String busareadesc2,
        String busarea3,
        String busareaabbr3,
        String busareadesc3,
        String busarea4,
        String busareaabbr4,
        String busareadesc4,
        String leavingcode,
        String graduatestartdate,
        String localhirerehire,
        String localsupervisor,
        String linemanagerbrid,
        String brid,
        String personnelarea,
        String personnelareadesc,
        String busarea5,
        String busareaabbr5,
        String busareadesc5,
        String subfunction,
        String subfunctiondesc,
        String function,
        String functiondesc,
        String sapcostcentretext,
        String companycode,
        String companycodetxt,
        String operationalstatusind,
        String citizencard,
        String evetelephoneno,
        String identificationcard,
        String pannumber,
        String nationalidcardno,
        String labourcardnumberid,
        String personalmobceltelephoneno,
        String employmentpass,
        String singaporeblue,
        String passport,
        String hongkongidentityno,
        String uniquenationalid,
        String singaporepink,
        String visaworkpermitreftier2,
        String busarea6,
        String busareaabbr6,
        String busareadesc6,
        String busarea7,
        String busareaabbr7,
        String busareadesc7,
        String busarea8,
        String busareaabbr8,
        String busareadesc8,
        String busarea9,
        String busareaabbr9,
        String busareadesc9,
        String busarea10,
        String busareaabbr10,
        String busareadesc10,
        String opnonopstatusreason,
        String opnonopstartdate,
        String opnonopenddate) {
        this.sevendigitstaffid = sevendigitstaffid;
        this.forename = forename;
        this.surname = surname;
        this.sapcostcentrecompany = sapcostcentrecompany;
        this.startdt = startdt;
        this.enddt = enddt;
        this.corporatetitle = corporatetitle;
        this.globallevel = globallevel;
        this.stafftype = stafftype;
        this.staffsubtype = staffsubtype;
        this.staffstatus = staffstatus;
        this.staffclass = staffclass;
        this.globalstaffid = globalstaffid;
        this.taxnumber = taxnumber;
        this.orgunit = orgunit;
        this.orgunitabbv = orgunitabbv;
        this.orgunitdesc = orgunitdesc;
        this.dept = dept;
        this.deptabbv = deptabbv;
        this.deptdesc = deptdesc;
        this.buildingdesc = buildingdesc;
        this.countrydesc = countrydesc;
        this.firstname = firstname;
        this.jobkey = jobkey;
        this.linemanagerid = linemanagerid;
        this.previouslastname = previouslastname;
        this.gender = gender;
        this.lastdayworked = lastdayworked;
        this.emailaddr = emailaddr;
        this.previouscostcentre = previouscostcentre;
        this.lastdaypaid = lastdaypaid;
        this.dateofbirth = dateofbirth;
        this.nationalitycode = nationalitycode;
        this.maternitydatefrom = maternitydatefrom;
        this.maternitydateto = maternitydateto;
        this.absence = absence;
        this.entitycode = entitycode;
        this.entitytext = entitytext;
        this.busarea1 = busarea1;
        this.busareaabbr1 = busareaabbr1;
        this.busareadesc1 = busareadesc1;
        this.busarea2 = busarea2;
        this.busareaabbr2 = busareaabbr2;
        this.busareadesc2 = busareadesc2;
        this.busarea3 = busarea3;
        this.busareaabbr3 = busareaabbr3;
        this.busareadesc3 = busareadesc3;
        this.busarea4 = busarea4;
        this.busareaabbr4 = busareaabbr4;
        this.busareadesc4 = busareadesc4;
        this.leavingcode = leavingcode;
        this.graduatestartdate = graduatestartdate;
        this.localhirerehire = localhirerehire;
        this.localsupervisor = localsupervisor;
        this.linemanagerbrid = linemanagerbrid;
        this.brid = brid;
        this.personnelarea = personnelarea;
        this.personnelareadesc = personnelareadesc;
        this.busarea5 = busarea5;
        this.busareaabbr5 = busareaabbr5;
        this.busareadesc5 = busareadesc5;
        this.subfunction = subfunction;
        this.subfunctiondesc = subfunctiondesc;
        this.function = function;
        this.functiondesc = functiondesc;
        this.sapcostcentretext = sapcostcentretext;
        this.companycode = companycode;
        this.companycodetxt = companycodetxt;
        this.operationalstatusind = operationalstatusind;
        this.citizencard = citizencard;
        this.evetelephoneno = evetelephoneno;
        this.identificationcard = identificationcard;
        this.pannumber = pannumber;
        this.nationalidcardno = nationalidcardno;
        this.labourcardnumberid = labourcardnumberid;
        this.personalmobceltelephoneno = personalmobceltelephoneno;
        this.employmentpass = employmentpass;
        this.singaporeblue = singaporeblue;
        this.passport = passport;
        this.hongkongidentityno = hongkongidentityno;
        this.uniquenationalid = uniquenationalid;
        this.singaporepink = singaporepink;
        this.visaworkpermitreftier2 = visaworkpermitreftier2;
        this.busarea6 = busarea6;
        this.busareaabbr6 = busareaabbr6;
        this.busareadesc6 = busareadesc6;
        this.busarea7 = busarea7;
        this.busareaabbr7 = busareaabbr7;
        this.busareadesc7 = busareadesc7;
        this.busarea8 = busarea8;
        this.busareaabbr8 = busareaabbr8;
        this.busareadesc8 = busareadesc8;
        this.busarea9 = busarea9;
        this.busareaabbr9 = busareaabbr9;
        this.busareadesc9 = busareadesc9;
        this.busarea10 = busarea10;
        this.busareaabbr10 = busareaabbr10;
        this.busareadesc10 = busareadesc10;
        this.opnonopstatusreason = opnonopstatusreason;
        this.opnonopstartdate = opnonopstartdate;
        this.opnonopenddate = opnonopenddate;
    }

    /**
     * Gets sevendigitstaffid
     * 
     * @return Value for sevendigitstaffid.
     **/
    public Long getSevendigitstaffid() {
        return sevendigitstaffid;
    }

    /**
     * Sets sevendigitstaffid
     * 
     * @param sevendigitstaffid New value for sevendigitstaffid.
     **/
    public void setSevendigitstaffid(Long sevendigitstaffid) {
        this.sevendigitstaffid = sevendigitstaffid;
    }

    /**
     * Gets forename
     * 
     * @return Value for forename.
     **/
    public String getForename() {
        return forename;
    }

    /**
     * Sets forename
     * 
     * @param forename New value for forename.
     **/
    public void setForename(String forename) {
        this.forename = forename;
    }

    /**
     * Gets surname
     * 
     * @return Value for surname.
     **/
    public String getSurname() {
        return surname;
    }

    /**
     * Sets surname
     * 
     * @param surname New value for surname.
     **/
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * Gets sapcostcentrecompany
     * 
     * @return Value for sapcostcentrecompany.
     **/
    public String getSapcostcentrecompany() {
        return sapcostcentrecompany;
    }

    /**
     * Sets sapcostcentrecompany
     * 
     * @param sapcostcentrecompany New value for sapcostcentrecompany.
     **/
    public void setSapcostcentrecompany(String sapcostcentrecompany) {
        this.sapcostcentrecompany = sapcostcentrecompany;
    }

    /**
     * Gets startdt
     * 
     * @return Value for startdt.
     **/
    public String getStartdt() {
        return startdt;
    }

    /**
     * Sets startdt
     * 
     * @param startdt New value for startdt.
     **/
    public void setStartdt(String startdt) {
        this.startdt = startdt;
    }

    /**
     * Gets enddt
     * 
     * @return Value for enddt.
     **/
    public String getEnddt() {
        return enddt;
    }

    /**
     * Sets enddt
     * 
     * @param enddt New value for enddt.
     **/
    public void setEnddt(String enddt) {
        this.enddt = enddt;
    }

    /**
     * Gets corporatetitle
     * 
     * @return Value for corporatetitle.
     **/
    public String getCorporatetitle() {
        return corporatetitle;
    }

    /**
     * Sets corporatetitle
     * 
     * @param corporatetitle New value for corporatetitle.
     **/
    public void setCorporatetitle(String corporatetitle) {
        this.corporatetitle = corporatetitle;
    }

    /**
     * Gets globallevel
     * 
     * @return Value for globallevel.
     **/
    public String getGloballevel() {
        return globallevel;
    }

    /**
     * Sets globallevel
     * 
     * @param globallevel New value for globallevel.
     **/
    public void setGloballevel(String globallevel) {
        this.globallevel = globallevel;
    }

    /**
     * Gets stafftype
     * 
     * @return Value for stafftype.
     **/
    public String getStafftype() {
        return stafftype;
    }

    /**
     * Sets stafftype
     * 
     * @param stafftype New value for stafftype.
     **/
    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }

    /**
     * Gets staffsubtype
     * 
     * @return Value for staffsubtype.
     **/
    public String getStaffsubtype() {
        return staffsubtype;
    }

    /**
     * Sets staffsubtype
     * 
     * @param staffsubtype New value for staffsubtype.
     **/
    public void setStaffsubtype(String staffsubtype) {
        this.staffsubtype = staffsubtype;
    }

    /**
     * Gets staffstatus
     * 
     * @return Value for staffstatus.
     **/
    public String getStaffstatus() {
        return staffstatus;
    }

    /**
     * Sets staffstatus
     * 
     * @param staffstatus New value for staffstatus.
     **/
    public void setStaffstatus(String staffstatus) {
        this.staffstatus = staffstatus;
    }

    /**
     * Gets staffclass
     * 
     * @return Value for staffclass.
     **/
    public String getStaffclass() {
        return staffclass;
    }

    /**
     * Sets staffclass
     * 
     * @param staffclass New value for staffclass.
     **/
    public void setStaffclass(String staffclass) {
        this.staffclass = staffclass;
    }

    /**
     * Gets globalstaffid
     * 
     * @return Value for globalstaffid.
     **/
    public Long getGlobalstaffid() {
        return globalstaffid;
    }

    /**
     * Sets globalstaffid
     * 
     * @param globalstaffid New value for globalstaffid.
     **/
    public void setGlobalstaffid(Long globalstaffid) {
        this.globalstaffid = globalstaffid;
    }

    /**
     * Gets taxnumber
     * 
     * @return Value for taxnumber.
     **/
    public String getTaxnumber() {
        return taxnumber;
    }

    /**
     * Sets taxnumber
     * 
     * @param taxnumber New value for taxnumber.
     **/
    public void setTaxnumber(String taxnumber) {
        this.taxnumber = taxnumber;
    }

    /**
     * Gets orgunit
     * 
     * @return Value for orgunit.
     **/
    public String getOrgunit() {
        return orgunit;
    }

    /**
     * Sets orgunit
     * 
     * @param orgunit New value for orgunit.
     **/
    public void setOrgunit(String orgunit) {
        this.orgunit = orgunit;
    }

    /**
     * Gets orgunitabbv
     * 
     * @return Value for orgunitabbv.
     **/
    public String getOrgunitabbv() {
        return orgunitabbv;
    }

    /**
     * Sets orgunitabbv
     * 
     * @param orgunitabbv New value for orgunitabbv.
     **/
    public void setOrgunitabbv(String orgunitabbv) {
        this.orgunitabbv = orgunitabbv;
    }

    /**
     * Gets orgunitdesc
     * 
     * @return Value for orgunitdesc.
     **/
    public String getOrgunitdesc() {
        return orgunitdesc;
    }

    /**
     * Sets orgunitdesc
     * 
     * @param orgunitdesc New value for orgunitdesc.
     **/
    public void setOrgunitdesc(String orgunitdesc) {
        this.orgunitdesc = orgunitdesc;
    }

    /**
     * Gets dept
     * 
     * @return Value for dept.
     **/
    public String getDept() {
        return dept;
    }

    /**
     * Sets dept
     * 
     * @param dept New value for dept.
     **/
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * Gets deptabbv
     * 
     * @return Value for deptabbv.
     **/
    public String getDeptabbv() {
        return deptabbv;
    }

    /**
     * Sets deptabbv
     * 
     * @param deptabbv New value for deptabbv.
     **/
    public void setDeptabbv(String deptabbv) {
        this.deptabbv = deptabbv;
    }

    /**
     * Gets deptdesc
     * 
     * @return Value for deptdesc.
     **/
    public String getDeptdesc() {
        return deptdesc;
    }

    /**
     * Sets deptdesc
     * 
     * @param deptdesc New value for deptdesc.
     **/
    public void setDeptdesc(String deptdesc) {
        this.deptdesc = deptdesc;
    }

    /**
     * Gets buildingdesc
     * 
     * @return Value for buildingdesc.
     **/
    public String getBuildingdesc() {
        return buildingdesc;
    }

    /**
     * Sets buildingdesc
     * 
     * @param buildingdesc New value for buildingdesc.
     **/
    public void setBuildingdesc(String buildingdesc) {
        this.buildingdesc = buildingdesc;
    }

    /**
     * Gets countrydesc
     * 
     * @return Value for countrydesc.
     **/
    public String getCountrydesc() {
        return countrydesc;
    }

    /**
     * Sets countrydesc
     * 
     * @param countrydesc New value for countrydesc.
     **/
    public void setCountrydesc(String countrydesc) {
        this.countrydesc = countrydesc;
    }

    /**
     * Gets firstname
     * 
     * @return Value for firstname.
     **/
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets firstname
     * 
     * @param firstname New value for firstname.
     **/
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * Gets jobkey
     * 
     * @return Value for jobkey.
     **/
    public String getJobkey() {
        return jobkey;
    }

    /**
     * Sets jobkey
     * 
     * @param jobkey New value for jobkey.
     **/
    public void setJobkey(String jobkey) {
        this.jobkey = jobkey;
    }

    /**
     * Gets linemanagerid
     * 
     * @return Value for linemanagerid.
     **/
    public String getLinemanagerid() {
        return linemanagerid;
    }

    /**
     * Sets linemanagerid
     * 
     * @param linemanagerid New value for linemanagerid.
     **/
    public void setLinemanagerid(String linemanagerid) {
        this.linemanagerid = linemanagerid;
    }

    /**
     * Gets previouslastname
     * 
     * @return Value for previouslastname.
     **/
    public String getPreviouslastname() {
        return previouslastname;
    }

    /**
     * Sets previouslastname
     * 
     * @param previouslastname New value for previouslastname.
     **/
    public void setPreviouslastname(String previouslastname) {
        this.previouslastname = previouslastname;
    }

    /**
     * Gets gender
     * 
     * @return Value for gender.
     **/
    public String getGender() {
        return gender;
    }

    /**
     * Sets gender
     * 
     * @param gender New value for gender.
     **/
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Gets lastdayworked
     * 
     * @return Value for lastdayworked.
     **/
    public String getLastdayworked() {
        return lastdayworked;
    }

    /**
     * Sets lastdayworked
     * 
     * @param lastdayworked New value for lastdayworked.
     **/
    public void setLastdayworked(String lastdayworked) {
        this.lastdayworked = lastdayworked;
    }

    /**
     * Gets emailaddr
     * 
     * @return Value for emailaddr.
     **/
    public String getEmailaddr() {
        return emailaddr;
    }

    /**
     * Sets emailaddr
     * 
     * @param emailaddr New value for emailaddr.
     **/
    public void setEmailaddr(String emailaddr) {
        this.emailaddr = emailaddr;
    }

    /**
     * Gets previouscostcentre
     * 
     * @return Value for previouscostcentre.
     **/
    public String getPreviouscostcentre() {
        return previouscostcentre;
    }

    /**
     * Sets previouscostcentre
     * 
     * @param previouscostcentre New value for previouscostcentre.
     **/
    public void setPreviouscostcentre(String previouscostcentre) {
        this.previouscostcentre = previouscostcentre;
    }

    /**
     * Gets lastdaypaid
     * 
     * @return Value for lastdaypaid.
     **/
    public String getLastdaypaid() {
        return lastdaypaid;
    }

    /**
     * Sets lastdaypaid
     * 
     * @param lastdaypaid New value for lastdaypaid.
     **/
    public void setLastdaypaid(String lastdaypaid) {
        this.lastdaypaid = lastdaypaid;
    }

    /**
     * Gets dateofbirth
     * 
     * @return Value for dateofbirth.
     **/
    public String getDateofbirth() {
        return dateofbirth;
    }

    /**
     * Sets dateofbirth
     * 
     * @param dateofbirth New value for dateofbirth.
     **/
    public void setDateofbirth(String dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    /**
     * Gets nationalitycode
     * 
     * @return Value for nationalitycode.
     **/
    public String getNationalitycode() {
        return nationalitycode;
    }

    /**
     * Sets nationalitycode
     * 
     * @param nationalitycode New value for nationalitycode.
     **/
    public void setNationalitycode(String nationalitycode) {
        this.nationalitycode = nationalitycode;
    }

    /**
     * Gets maternitydatefrom
     * 
     * @return Value for maternitydatefrom.
     **/
    public String getMaternitydatefrom() {
        return maternitydatefrom;
    }

    /**
     * Sets maternitydatefrom
     * 
     * @param maternitydatefrom New value for maternitydatefrom.
     **/
    public void setMaternitydatefrom(String maternitydatefrom) {
        this.maternitydatefrom = maternitydatefrom;
    }

    /**
     * Gets maternitydateto
     * 
     * @return Value for maternitydateto.
     **/
    public String getMaternitydateto() {
        return maternitydateto;
    }

    /**
     * Sets maternitydateto
     * 
     * @param maternitydateto New value for maternitydateto.
     **/
    public void setMaternitydateto(String maternitydateto) {
        this.maternitydateto = maternitydateto;
    }

    /**
     * Gets absence
     * 
     * @return Value for absence.
     **/
    public String getAbsence() {
        return absence;
    }

    /**
     * Sets absence
     * 
     * @param absence New value for absence.
     **/
    public void setAbsence(String absence) {
        this.absence = absence;
    }

    /**
     * Gets entitycode
     * 
     * @return Value for entitycode.
     **/
    public String getEntitycode() {
        return entitycode;
    }

    /**
     * Sets entitycode
     * 
     * @param entitycode New value for entitycode.
     **/
    public void setEntitycode(String entitycode) {
        this.entitycode = entitycode;
    }

    /**
     * Gets entitytext
     * 
     * @return Value for entitytext.
     **/
    public String getEntitytext() {
        return entitytext;
    }

    /**
     * Sets entitytext
     * 
     * @param entitytext New value for entitytext.
     **/
    public void setEntitytext(String entitytext) {
        this.entitytext = entitytext;
    }

    /**
     * Gets busarea1
     * 
     * @return Value for busarea1.
     **/
    public String getBusarea1() {
        return busarea1;
    }

    /**
     * Sets busarea1
     * 
     * @param busarea1 New value for busarea1.
     **/
    public void setBusarea1(String busarea1) {
        this.busarea1 = busarea1;
    }

    /**
     * Gets busareaabbr1
     * 
     * @return Value for busareaabbr1.
     **/
    public String getBusareaabbr1() {
        return busareaabbr1;
    }

    /**
     * Sets busareaabbr1
     * 
     * @param busareaabbr1 New value for busareaabbr1.
     **/
    public void setBusareaabbr1(String busareaabbr1) {
        this.busareaabbr1 = busareaabbr1;
    }

    /**
     * Gets busareadesc1
     * 
     * @return Value for busareadesc1.
     **/
    public String getBusareadesc1() {
        return busareadesc1;
    }

    /**
     * Sets busareadesc1
     * 
     * @param busareadesc1 New value for busareadesc1.
     **/
    public void setBusareadesc1(String busareadesc1) {
        this.busareadesc1 = busareadesc1;
    }

    /**
     * Gets busarea2
     * 
     * @return Value for busarea2.
     **/
    public String getBusarea2() {
        return busarea2;
    }

    /**
     * Sets busarea2
     * 
     * @param busarea2 New value for busarea2.
     **/
    public void setBusarea2(String busarea2) {
        this.busarea2 = busarea2;
    }

    /**
     * Gets busareaabbr2
     * 
     * @return Value for busareaabbr2.
     **/
    public String getBusareaabbr2() {
        return busareaabbr2;
    }

    /**
     * Sets busareaabbr2
     * 
     * @param busareaabbr2 New value for busareaabbr2.
     **/
    public void setBusareaabbr2(String busareaabbr2) {
        this.busareaabbr2 = busareaabbr2;
    }

    /**
     * Gets busareadesc2
     * 
     * @return Value for busareadesc2.
     **/
    public String getBusareadesc2() {
        return busareadesc2;
    }

    /**
     * Sets busareadesc2
     * 
     * @param busareadesc2 New value for busareadesc2.
     **/
    public void setBusareadesc2(String busareadesc2) {
        this.busareadesc2 = busareadesc2;
    }

    /**
     * Gets busarea3
     * 
     * @return Value for busarea3.
     **/
    public String getBusarea3() {
        return busarea3;
    }

    /**
     * Sets busarea3
     * 
     * @param busarea3 New value for busarea3.
     **/
    public void setBusarea3(String busarea3) {
        this.busarea3 = busarea3;
    }

    /**
     * Gets busareaabbr3
     * 
     * @return Value for busareaabbr3.
     **/
    public String getBusareaabbr3() {
        return busareaabbr3;
    }

    /**
     * Sets busareaabbr3
     * 
     * @param busareaabbr3 New value for busareaabbr3.
     **/
    public void setBusareaabbr3(String busareaabbr3) {
        this.busareaabbr3 = busareaabbr3;
    }

    /**
     * Gets busareadesc3
     * 
     * @return Value for busareadesc3.
     **/
    public String getBusareadesc3() {
        return busareadesc3;
    }

    /**
     * Sets busareadesc3
     * 
     * @param busareadesc3 New value for busareadesc3.
     **/
    public void setBusareadesc3(String busareadesc3) {
        this.busareadesc3 = busareadesc3;
    }

    /**
     * Gets busarea4
     * 
     * @return Value for busarea4.
     **/
    public String getBusarea4() {
        return busarea4;
    }

    /**
     * Sets busarea4
     * 
     * @param busarea4 New value for busarea4.
     **/
    public void setBusarea4(String busarea4) {
        this.busarea4 = busarea4;
    }

    /**
     * Gets busareaabbr4
     * 
     * @return Value for busareaabbr4.
     **/
    public String getBusareaabbr4() {
        return busareaabbr4;
    }

    /**
     * Sets busareaabbr4
     * 
     * @param busareaabbr4 New value for busareaabbr4.
     **/
    public void setBusareaabbr4(String busareaabbr4) {
        this.busareaabbr4 = busareaabbr4;
    }

    /**
     * Gets busareadesc4
     * 
     * @return Value for busareadesc4.
     **/
    public String getBusareadesc4() {
        return busareadesc4;
    }

    /**
     * Sets busareadesc4
     * 
     * @param busareadesc4 New value for busareadesc4.
     **/
    public void setBusareadesc4(String busareadesc4) {
        this.busareadesc4 = busareadesc4;
    }

    /**
     * Gets leavingcode
     * 
     * @return Value for leavingcode.
     **/
    public String getLeavingcode() {
        return leavingcode;
    }

    /**
     * Sets leavingcode
     * 
     * @param leavingcode New value for leavingcode.
     **/
    public void setLeavingcode(String leavingcode) {
        this.leavingcode = leavingcode;
    }

    /**
     * Gets graduatestartdate
     * 
     * @return Value for graduatestartdate.
     **/
    public String getGraduatestartdate() {
        return graduatestartdate;
    }

    /**
     * Sets graduatestartdate
     * 
     * @param graduatestartdate New value for graduatestartdate.
     **/
    public void setGraduatestartdate(String graduatestartdate) {
        this.graduatestartdate = graduatestartdate;
    }

    /**
     * Gets localhirerehire
     * 
     * @return Value for localhirerehire.
     **/
    public String getLocalhirerehire() {
        return localhirerehire;
    }

    /**
     * Sets localhirerehire
     * 
     * @param localhirerehire New value for localhirerehire.
     **/
    public void setLocalhirerehire(String localhirerehire) {
        this.localhirerehire = localhirerehire;
    }

    /**
     * Gets localsupervisor
     * 
     * @return Value for localsupervisor.
     **/
    public String getLocalsupervisor() {
        return localsupervisor;
    }

    /**
     * Sets localsupervisor
     * 
     * @param localsupervisor New value for localsupervisor.
     **/
    public void setLocalsupervisor(String localsupervisor) {
        this.localsupervisor = localsupervisor;
    }

    /**
     * Gets linemanagerbrid
     * 
     * @return Value for linemanagerbrid.
     **/
    public String getLinemanagerbrid() {
        return linemanagerbrid;
    }

    /**
     * Sets linemanagerbrid
     * 
     * @param linemanagerbrid New value for linemanagerbrid.
     **/
    public void setLinemanagerbrid(String linemanagerbrid) {
        this.linemanagerbrid = linemanagerbrid;
    }

    /**
     * Gets brid
     * 
     * @return Value for brid.
     **/
    public String getBrid() {
        return brid;
    }

    /**
     * Sets brid
     * 
     * @param brid New value for brid.
     **/
    public void setBrid(String brid) {
        this.brid = brid;
    }

    /**
     * Gets personnelarea
     * 
     * @return Value for personnelarea.
     **/
    public String getPersonnelarea() {
        return personnelarea;
    }

    /**
     * Sets personnelarea
     * 
     * @param personnelarea New value for personnelarea.
     **/
    public void setPersonnelarea(String personnelarea) {
        this.personnelarea = personnelarea;
    }

    /**
     * Gets personnelareadesc
     * 
     * @return Value for personnelareadesc.
     **/
    public String getPersonnelareadesc() {
        return personnelareadesc;
    }

    /**
     * Sets personnelareadesc
     * 
     * @param personnelareadesc New value for personnelareadesc.
     **/
    public void setPersonnelareadesc(String personnelareadesc) {
        this.personnelareadesc = personnelareadesc;
    }

    /**
     * Gets busarea5
     * 
     * @return Value for busarea5.
     **/
    public String getBusarea5() {
        return busarea5;
    }

    /**
     * Sets busarea5
     * 
     * @param busarea5 New value for busarea5.
     **/
    public void setBusarea5(String busarea5) {
        this.busarea5 = busarea5;
    }

    /**
     * Gets busareaabbr5
     * 
     * @return Value for busareaabbr5.
     **/
    public String getBusareaabbr5() {
        return busareaabbr5;
    }

    /**
     * Sets busareaabbr5
     * 
     * @param busareaabbr5 New value for busareaabbr5.
     **/
    public void setBusareaabbr5(String busareaabbr5) {
        this.busareaabbr5 = busareaabbr5;
    }

    /**
     * Gets busareadesc5
     * 
     * @return Value for busareadesc5.
     **/
    public String getBusareadesc5() {
        return busareadesc5;
    }

    /**
     * Sets busareadesc5
     * 
     * @param busareadesc5 New value for busareadesc5.
     **/
    public void setBusareadesc5(String busareadesc5) {
        this.busareadesc5 = busareadesc5;
    }

    /**
     * Gets subfunction
     * 
     * @return Value for subfunction.
     **/
    public String getSubfunction() {
        return subfunction;
    }

    /**
     * Sets subfunction
     * 
     * @param subfunction New value for subfunction.
     **/
    public void setSubfunction(String subfunction) {
        this.subfunction = subfunction;
    }

    /**
     * Gets subfunctiondesc
     * 
     * @return Value for subfunctiondesc.
     **/
    public String getSubfunctiondesc() {
        return subfunctiondesc;
    }

    /**
     * Sets subfunctiondesc
     * 
     * @param subfunctiondesc New value for subfunctiondesc.
     **/
    public void setSubfunctiondesc(String subfunctiondesc) {
        this.subfunctiondesc = subfunctiondesc;
    }

    /**
     * Gets function
     * 
     * @return Value for function.
     **/
    public String getFunction() {
        return function;
    }

    /**
     * Sets function
     * 
     * @param function New value for function.
     **/
    public void setFunction(String function) {
        this.function = function;
    }

    /**
     * Gets functiondesc
     * 
     * @return Value for functiondesc.
     **/
    public String getFunctiondesc() {
        return functiondesc;
    }

    /**
     * Sets functiondesc
     * 
     * @param functiondesc New value for functiondesc.
     **/
    public void setFunctiondesc(String functiondesc) {
        this.functiondesc = functiondesc;
    }

    /**
     * Gets sapcostcentretext
     * 
     * @return Value for sapcostcentretext.
     **/
    public String getSapcostcentretext() {
        return sapcostcentretext;
    }

    /**
     * Sets sapcostcentretext
     * 
     * @param sapcostcentretext New value for sapcostcentretext.
     **/
    public void setSapcostcentretext(String sapcostcentretext) {
        this.sapcostcentretext = sapcostcentretext;
    }

    /**
     * Gets companycode
     * 
     * @return Value for companycode.
     **/
    public String getCompanycode() {
        return companycode;
    }

    /**
     * Sets companycode
     * 
     * @param companycode New value for companycode.
     **/
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }

    /**
     * Gets companycodetxt
     * 
     * @return Value for companycodetxt.
     **/
    public String getCompanycodetxt() {
        return companycodetxt;
    }

    /**
     * Sets companycodetxt
     * 
     * @param companycodetxt New value for companycodetxt.
     **/
    public void setCompanycodetxt(String companycodetxt) {
        this.companycodetxt = companycodetxt;
    }

    /**
     * Gets operationalstatusind
     * 
     * @return Value for operationalstatusind.
     **/
    public String getOperationalstatusind() {
        return operationalstatusind;
    }

    /**
     * Sets operationalstatusind
     * 
     * @param operationalstatusind New value for operationalstatusind.
     **/
    public void setOperationalstatusind(String operationalstatusind) {
        this.operationalstatusind = operationalstatusind;
    }

    /**
     * Gets citizencard
     * 
     * @return Value for citizencard.
     **/
    public String getCitizencard() {
        return citizencard;
    }

    /**
     * Sets citizencard
     * 
     * @param citizencard New value for citizencard.
     **/
    public void setCitizencard(String citizencard) {
        this.citizencard = citizencard;
    }

    /**
     * Gets evetelephoneno
     * 
     * @return Value for evetelephoneno.
     **/
    public String getEvetelephoneno() {
        return evetelephoneno;
    }

    /**
     * Sets evetelephoneno
     * 
     * @param evetelephoneno New value for evetelephoneno.
     **/
    public void setEvetelephoneno(String evetelephoneno) {
        this.evetelephoneno = evetelephoneno;
    }

    /**
     * Gets identificationcard
     * 
     * @return Value for identificationcard.
     **/
    public String getIdentificationcard() {
        return identificationcard;
    }

    /**
     * Sets identificationcard
     * 
     * @param identificationcard New value for identificationcard.
     **/
    public void setIdentificationcard(String identificationcard) {
        this.identificationcard = identificationcard;
    }

    /**
     * Gets pannumber
     * 
     * @return Value for pannumber.
     **/
    public String getPannumber() {
        return pannumber;
    }

    /**
     * Sets pannumber
     * 
     * @param pannumber New value for pannumber.
     **/
    public void setPannumber(String pannumber) {
        this.pannumber = pannumber;
    }

    /**
     * Gets nationalidcardno
     * 
     * @return Value for nationalidcardno.
     **/
    public String getNationalidcardno() {
        return nationalidcardno;
    }

    /**
     * Sets nationalidcardno
     * 
     * @param nationalidcardno New value for nationalidcardno.
     **/
    public void setNationalidcardno(String nationalidcardno) {
        this.nationalidcardno = nationalidcardno;
    }

    /**
     * Gets labourcardnumberid
     * 
     * @return Value for labourcardnumberid.
     **/
    public String getLabourcardnumberid() {
        return labourcardnumberid;
    }

    /**
     * Sets labourcardnumberid
     * 
     * @param labourcardnumberid New value for labourcardnumberid.
     **/
    public void setLabourcardnumberid(String labourcardnumberid) {
        this.labourcardnumberid = labourcardnumberid;
    }

    /**
     * Gets personalmobceltelephoneno
     * 
     * @return Value for personalmobceltelephoneno.
     **/
    public String getPersonalmobceltelephoneno() {
        return personalmobceltelephoneno;
    }

    /**
     * Sets personalmobceltelephoneno
     * 
     * @param personalmobceltelephoneno New value for personalmobceltelephoneno.
     **/
    public void setPersonalmobceltelephoneno(String personalmobceltelephoneno) {
        this.personalmobceltelephoneno = personalmobceltelephoneno;
    }

    /**
     * Gets employmentpass
     * 
     * @return Value for employmentpass.
     **/
    public String getEmploymentpass() {
        return employmentpass;
    }

    /**
     * Sets employmentpass
     * 
     * @param employmentpass New value for employmentpass.
     **/
    public void setEmploymentpass(String employmentpass) {
        this.employmentpass = employmentpass;
    }

    /**
     * Gets singaporeblue
     * 
     * @return Value for singaporeblue.
     **/
    public String getSingaporeblue() {
        return singaporeblue;
    }

    /**
     * Sets singaporeblue
     * 
     * @param singaporeblue New value for singaporeblue.
     **/
    public void setSingaporeblue(String singaporeblue) {
        this.singaporeblue = singaporeblue;
    }

    /**
     * Gets passport
     * 
     * @return Value for passport.
     **/
    public String getPassport() {
        return passport;
    }

    /**
     * Sets passport
     * 
     * @param passport New value for passport.
     **/
    public void setPassport(String passport) {
        this.passport = passport;
    }

    /**
     * Gets hongkongidentityno
     * 
     * @return Value for hongkongidentityno.
     **/
    public String getHongkongidentityno() {
        return hongkongidentityno;
    }

    /**
     * Sets hongkongidentityno
     * 
     * @param hongkongidentityno New value for hongkongidentityno.
     **/
    public void setHongkongidentityno(String hongkongidentityno) {
        this.hongkongidentityno = hongkongidentityno;
    }

    /**
     * Gets uniquenationalid
     * 
     * @return Value for uniquenationalid.
     **/
    public String getUniquenationalid() {
        return uniquenationalid;
    }

    /**
     * Sets uniquenationalid
     * 
     * @param uniquenationalid New value for uniquenationalid.
     **/
    public void setUniquenationalid(String uniquenationalid) {
        this.uniquenationalid = uniquenationalid;
    }

    /**
     * Gets singaporepink
     * 
     * @return Value for singaporepink.
     **/
    public String getSingaporepink() {
        return singaporepink;
    }

    /**
     * Sets singaporepink
     * 
     * @param singaporepink New value for singaporepink.
     **/
    public void setSingaporepink(String singaporepink) {
        this.singaporepink = singaporepink;
    }

    /**
     * Gets visaworkpermitreftier2
     * 
     * @return Value for visaworkpermitreftier2.
     **/
    public String getVisaworkpermitreftier2() {
        return visaworkpermitreftier2;
    }

    /**
     * Sets visaworkpermitreftier2
     * 
     * @param visaworkpermitreftier2 New value for visaworkpermitreftier2.
     **/
    public void setVisaworkpermitreftier2(String visaworkpermitreftier2) {
        this.visaworkpermitreftier2 = visaworkpermitreftier2;
    }

    /**
     * Gets busarea6
     * 
     * @return Value for busarea6.
     **/
    public String getBusarea6() {
        return busarea6;
    }

    /**
     * Sets busarea6
     * 
     * @param busarea6 New value for busarea6.
     **/
    public void setBusarea6(String busarea6) {
        this.busarea6 = busarea6;
    }

    /**
     * Gets busareaabbr6
     * 
     * @return Value for busareaabbr6.
     **/
    public String getBusareaabbr6() {
        return busareaabbr6;
    }

    /**
     * Sets busareaabbr6
     * 
     * @param busareaabbr6 New value for busareaabbr6.
     **/
    public void setBusareaabbr6(String busareaabbr6) {
        this.busareaabbr6 = busareaabbr6;
    }

    /**
     * Gets busareadesc6
     * 
     * @return Value for busareadesc6.
     **/
    public String getBusareadesc6() {
        return busareadesc6;
    }

    /**
     * Sets busareadesc6
     * 
     * @param busareadesc6 New value for busareadesc6.
     **/
    public void setBusareadesc6(String busareadesc6) {
        this.busareadesc6 = busareadesc6;
    }

    /**
     * Gets busarea7
     * 
     * @return Value for busarea7.
     **/
    public String getBusarea7() {
        return busarea7;
    }

    /**
     * Sets busarea7
     * 
     * @param busarea7 New value for busarea7.
     **/
    public void setBusarea7(String busarea7) {
        this.busarea7 = busarea7;
    }

    /**
     * Gets busareaabbr7
     * 
     * @return Value for busareaabbr7.
     **/
    public String getBusareaabbr7() {
        return busareaabbr7;
    }

    /**
     * Sets busareaabbr7
     * 
     * @param busareaabbr7 New value for busareaabbr7.
     **/
    public void setBusareaabbr7(String busareaabbr7) {
        this.busareaabbr7 = busareaabbr7;
    }

    /**
     * Gets busareadesc7
     * 
     * @return Value for busareadesc7.
     **/
    public String getBusareadesc7() {
        return busareadesc7;
    }

    /**
     * Sets busareadesc7
     * 
     * @param busareadesc7 New value for busareadesc7.
     **/
    public void setBusareadesc7(String busareadesc7) {
        this.busareadesc7 = busareadesc7;
    }

    /**
     * Gets busarea8
     * 
     * @return Value for busarea8.
     **/
    public String getBusarea8() {
        return busarea8;
    }

    /**
     * Sets busarea8
     * 
     * @param busarea8 New value for busarea8.
     **/
    public void setBusarea8(String busarea8) {
        this.busarea8 = busarea8;
    }

    /**
     * Gets busareaabbr8
     * 
     * @return Value for busareaabbr8.
     **/
    public String getBusareaabbr8() {
        return busareaabbr8;
    }

    /**
     * Sets busareaabbr8
     * 
     * @param busareaabbr8 New value for busareaabbr8.
     **/
    public void setBusareaabbr8(String busareaabbr8) {
        this.busareaabbr8 = busareaabbr8;
    }

    /**
     * Gets busareadesc8
     * 
     * @return Value for busareadesc8.
     **/
    public String getBusareadesc8() {
        return busareadesc8;
    }

    /**
     * Sets busareadesc8
     * 
     * @param busareadesc8 New value for busareadesc8.
     **/
    public void setBusareadesc8(String busareadesc8) {
        this.busareadesc8 = busareadesc8;
    }

    /**
     * Gets busarea9
     * 
     * @return Value for busarea9.
     **/
    public String getBusarea9() {
        return busarea9;
    }

    /**
     * Sets busarea9
     * 
     * @param busarea9 New value for busarea9.
     **/
    public void setBusarea9(String busarea9) {
        this.busarea9 = busarea9;
    }

    /**
     * Gets busareaabbr9
     * 
     * @return Value for busareaabbr9.
     **/
    public String getBusareaabbr9() {
        return busareaabbr9;
    }

    /**
     * Sets busareaabbr9
     * 
     * @param busareaabbr9 New value for busareaabbr9.
     **/
    public void setBusareaabbr9(String busareaabbr9) {
        this.busareaabbr9 = busareaabbr9;
    }

    /**
     * Gets busareadesc9
     * 
     * @return Value for busareadesc9.
     **/
    public String getBusareadesc9() {
        return busareadesc9;
    }

    /**
     * Sets busareadesc9
     * 
     * @param busareadesc9 New value for busareadesc9.
     **/
    public void setBusareadesc9(String busareadesc9) {
        this.busareadesc9 = busareadesc9;
    }

    /**
     * Gets busarea10
     * 
     * @return Value for busarea10.
     **/
    public String getBusarea10() {
        return busarea10;
    }

    /**
     * Sets busarea10
     * 
     * @param busarea10 New value for busarea10.
     **/
    public void setBusarea10(String busarea10) {
        this.busarea10 = busarea10;
    }

    /**
     * Gets busareaabbr10
     * 
     * @return Value for busareaabbr10.
     **/
    public String getBusareaabbr10() {
        return busareaabbr10;
    }

    /**
     * Sets busareaabbr10
     * 
     * @param busareaabbr10 New value for busareaabbr10.
     **/
    public void setBusareaabbr10(String busareaabbr10) {
        this.busareaabbr10 = busareaabbr10;
    }

    /**
     * Gets busareadesc10
     * 
     * @return Value for busareadesc10.
     **/
    public String getBusareadesc10() {
        return busareadesc10;
    }

    /**
     * Sets busareadesc10
     * 
     * @param busareadesc10 New value for busareadesc10.
     **/
    public void setBusareadesc10(String busareadesc10) {
        this.busareadesc10 = busareadesc10;
    }

    /**
     * Gets opnonopstatusreason
     * 
     * @return Value for opnonopstatusreason.
     **/
    public String getOpnonopstatusreason() {
        return opnonopstatusreason;
    }

    /**
     * Sets opnonopstatusreason
     * 
     * @param opnonopstatusreason New value for opnonopstatusreason.
     **/
    public void setOpnonopstatusreason(String opnonopstatusreason) {
        this.opnonopstatusreason = opnonopstatusreason;
    }

    /**
     * Gets opnonopstartdate
     * 
     * @return Value for opnonopstartdate.
     **/
    public String getOpnonopstartdate() {
        return opnonopstartdate;
    }

    /**
     * Sets opnonopstartdate
     * 
     * @param opnonopstartdate New value for opnonopstartdate.
     **/
    public void setOpnonopstartdate(String opnonopstartdate) {
        this.opnonopstartdate = opnonopstartdate;
    }

    /**
     * Gets opnonopenddate
     * 
     * @return Value for opnonopenddate.
     **/
    public String getOpnonopenddate() {
        return opnonopenddate;
    }

    /**
     * Sets opnonopenddate
     * 
     * @param opnonopenddate New value for opnonopenddate.
     **/
    public void setOpnonopenddate(String opnonopenddate) {
        this.opnonopenddate = opnonopenddate;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof FeedSapEmployee))
            return false;
        
        FeedSapEmployee that = (FeedSapEmployee)o;

        if (sevendigitstaffid != null ? !sevendigitstaffid.equals(that.sevendigitstaffid) : that.sevendigitstaffid != null)
            return false;
        

        if (forename != null ? !forename.equals(that.forename) : that.forename != null)
            return false;
        

        if (surname != null ? !surname.equals(that.surname) : that.surname != null)
            return false;
        

        if (sapcostcentrecompany != null ? !sapcostcentrecompany.equals(that.sapcostcentrecompany) : that.sapcostcentrecompany != null)
            return false;
        

        if (startdt != null ? !startdt.equals(that.startdt) : that.startdt != null)
            return false;
        

        if (enddt != null ? !enddt.equals(that.enddt) : that.enddt != null)
            return false;
        

        if (corporatetitle != null ? !corporatetitle.equals(that.corporatetitle) : that.corporatetitle != null)
            return false;
        

        if (globallevel != null ? !globallevel.equals(that.globallevel) : that.globallevel != null)
            return false;
        

        if (stafftype != null ? !stafftype.equals(that.stafftype) : that.stafftype != null)
            return false;
        

        if (staffsubtype != null ? !staffsubtype.equals(that.staffsubtype) : that.staffsubtype != null)
            return false;
        

        if (staffstatus != null ? !staffstatus.equals(that.staffstatus) : that.staffstatus != null)
            return false;
        

        if (staffclass != null ? !staffclass.equals(that.staffclass) : that.staffclass != null)
            return false;
        

        if (globalstaffid != null ? !globalstaffid.equals(that.globalstaffid) : that.globalstaffid != null)
            return false;
        

        if (taxnumber != null ? !taxnumber.equals(that.taxnumber) : that.taxnumber != null)
            return false;
        

        if (orgunit != null ? !orgunit.equals(that.orgunit) : that.orgunit != null)
            return false;
        

        if (orgunitabbv != null ? !orgunitabbv.equals(that.orgunitabbv) : that.orgunitabbv != null)
            return false;
        

        if (orgunitdesc != null ? !orgunitdesc.equals(that.orgunitdesc) : that.orgunitdesc != null)
            return false;
        

        if (dept != null ? !dept.equals(that.dept) : that.dept != null)
            return false;
        

        if (deptabbv != null ? !deptabbv.equals(that.deptabbv) : that.deptabbv != null)
            return false;
        

        if (deptdesc != null ? !deptdesc.equals(that.deptdesc) : that.deptdesc != null)
            return false;
        

        if (buildingdesc != null ? !buildingdesc.equals(that.buildingdesc) : that.buildingdesc != null)
            return false;
        

        if (countrydesc != null ? !countrydesc.equals(that.countrydesc) : that.countrydesc != null)
            return false;
        

        if (firstname != null ? !firstname.equals(that.firstname) : that.firstname != null)
            return false;
        

        if (jobkey != null ? !jobkey.equals(that.jobkey) : that.jobkey != null)
            return false;
        

        if (linemanagerid != null ? !linemanagerid.equals(that.linemanagerid) : that.linemanagerid != null)
            return false;
        

        if (previouslastname != null ? !previouslastname.equals(that.previouslastname) : that.previouslastname != null)
            return false;
        

        if (gender != null ? !gender.equals(that.gender) : that.gender != null)
            return false;
        

        if (lastdayworked != null ? !lastdayworked.equals(that.lastdayworked) : that.lastdayworked != null)
            return false;
        

        if (emailaddr != null ? !emailaddr.equals(that.emailaddr) : that.emailaddr != null)
            return false;
        

        if (previouscostcentre != null ? !previouscostcentre.equals(that.previouscostcentre) : that.previouscostcentre != null)
            return false;
        

        if (lastdaypaid != null ? !lastdaypaid.equals(that.lastdaypaid) : that.lastdaypaid != null)
            return false;
        

        if (dateofbirth != null ? !dateofbirth.equals(that.dateofbirth) : that.dateofbirth != null)
            return false;
        

        if (nationalitycode != null ? !nationalitycode.equals(that.nationalitycode) : that.nationalitycode != null)
            return false;
        

        if (maternitydatefrom != null ? !maternitydatefrom.equals(that.maternitydatefrom) : that.maternitydatefrom != null)
            return false;
        

        if (maternitydateto != null ? !maternitydateto.equals(that.maternitydateto) : that.maternitydateto != null)
            return false;
        

        if (absence != null ? !absence.equals(that.absence) : that.absence != null)
            return false;
        

        if (entitycode != null ? !entitycode.equals(that.entitycode) : that.entitycode != null)
            return false;
        

        if (entitytext != null ? !entitytext.equals(that.entitytext) : that.entitytext != null)
            return false;
        

        if (busarea1 != null ? !busarea1.equals(that.busarea1) : that.busarea1 != null)
            return false;
        

        if (busareaabbr1 != null ? !busareaabbr1.equals(that.busareaabbr1) : that.busareaabbr1 != null)
            return false;
        

        if (busareadesc1 != null ? !busareadesc1.equals(that.busareadesc1) : that.busareadesc1 != null)
            return false;
        

        if (busarea2 != null ? !busarea2.equals(that.busarea2) : that.busarea2 != null)
            return false;
        

        if (busareaabbr2 != null ? !busareaabbr2.equals(that.busareaabbr2) : that.busareaabbr2 != null)
            return false;
        

        if (busareadesc2 != null ? !busareadesc2.equals(that.busareadesc2) : that.busareadesc2 != null)
            return false;
        

        if (busarea3 != null ? !busarea3.equals(that.busarea3) : that.busarea3 != null)
            return false;
        

        if (busareaabbr3 != null ? !busareaabbr3.equals(that.busareaabbr3) : that.busareaabbr3 != null)
            return false;
        

        if (busareadesc3 != null ? !busareadesc3.equals(that.busareadesc3) : that.busareadesc3 != null)
            return false;
        

        if (busarea4 != null ? !busarea4.equals(that.busarea4) : that.busarea4 != null)
            return false;
        

        if (busareaabbr4 != null ? !busareaabbr4.equals(that.busareaabbr4) : that.busareaabbr4 != null)
            return false;
        

        if (busareadesc4 != null ? !busareadesc4.equals(that.busareadesc4) : that.busareadesc4 != null)
            return false;
        

        if (leavingcode != null ? !leavingcode.equals(that.leavingcode) : that.leavingcode != null)
            return false;
        

        if (graduatestartdate != null ? !graduatestartdate.equals(that.graduatestartdate) : that.graduatestartdate != null)
            return false;
        

        if (localhirerehire != null ? !localhirerehire.equals(that.localhirerehire) : that.localhirerehire != null)
            return false;
        

        if (localsupervisor != null ? !localsupervisor.equals(that.localsupervisor) : that.localsupervisor != null)
            return false;
        

        if (linemanagerbrid != null ? !linemanagerbrid.equals(that.linemanagerbrid) : that.linemanagerbrid != null)
            return false;
        

        if (brid != null ? !brid.equals(that.brid) : that.brid != null)
            return false;
        

        if (personnelarea != null ? !personnelarea.equals(that.personnelarea) : that.personnelarea != null)
            return false;
        

        if (personnelareadesc != null ? !personnelareadesc.equals(that.personnelareadesc) : that.personnelareadesc != null)
            return false;
        

        if (busarea5 != null ? !busarea5.equals(that.busarea5) : that.busarea5 != null)
            return false;
        

        if (busareaabbr5 != null ? !busareaabbr5.equals(that.busareaabbr5) : that.busareaabbr5 != null)
            return false;
        

        if (busareadesc5 != null ? !busareadesc5.equals(that.busareadesc5) : that.busareadesc5 != null)
            return false;
        

        if (subfunction != null ? !subfunction.equals(that.subfunction) : that.subfunction != null)
            return false;
        

        if (subfunctiondesc != null ? !subfunctiondesc.equals(that.subfunctiondesc) : that.subfunctiondesc != null)
            return false;
        

        if (function != null ? !function.equals(that.function) : that.function != null)
            return false;
        

        if (functiondesc != null ? !functiondesc.equals(that.functiondesc) : that.functiondesc != null)
            return false;
        

        if (sapcostcentretext != null ? !sapcostcentretext.equals(that.sapcostcentretext) : that.sapcostcentretext != null)
            return false;
        

        if (companycode != null ? !companycode.equals(that.companycode) : that.companycode != null)
            return false;
        

        if (companycodetxt != null ? !companycodetxt.equals(that.companycodetxt) : that.companycodetxt != null)
            return false;
        

        if (operationalstatusind != null ? !operationalstatusind.equals(that.operationalstatusind) : that.operationalstatusind != null)
            return false;
        

        if (citizencard != null ? !citizencard.equals(that.citizencard) : that.citizencard != null)
            return false;
        

        if (evetelephoneno != null ? !evetelephoneno.equals(that.evetelephoneno) : that.evetelephoneno != null)
            return false;
        

        if (identificationcard != null ? !identificationcard.equals(that.identificationcard) : that.identificationcard != null)
            return false;
        

        if (pannumber != null ? !pannumber.equals(that.pannumber) : that.pannumber != null)
            return false;
        

        if (nationalidcardno != null ? !nationalidcardno.equals(that.nationalidcardno) : that.nationalidcardno != null)
            return false;
        

        if (labourcardnumberid != null ? !labourcardnumberid.equals(that.labourcardnumberid) : that.labourcardnumberid != null)
            return false;
        

        if (personalmobceltelephoneno != null ? !personalmobceltelephoneno.equals(that.personalmobceltelephoneno) : that.personalmobceltelephoneno != null)
            return false;
        

        if (employmentpass != null ? !employmentpass.equals(that.employmentpass) : that.employmentpass != null)
            return false;
        

        if (singaporeblue != null ? !singaporeblue.equals(that.singaporeblue) : that.singaporeblue != null)
            return false;
        

        if (passport != null ? !passport.equals(that.passport) : that.passport != null)
            return false;
        

        if (hongkongidentityno != null ? !hongkongidentityno.equals(that.hongkongidentityno) : that.hongkongidentityno != null)
            return false;
        

        if (uniquenationalid != null ? !uniquenationalid.equals(that.uniquenationalid) : that.uniquenationalid != null)
            return false;
        

        if (singaporepink != null ? !singaporepink.equals(that.singaporepink) : that.singaporepink != null)
            return false;
        

        if (visaworkpermitreftier2 != null ? !visaworkpermitreftier2.equals(that.visaworkpermitreftier2) : that.visaworkpermitreftier2 != null)
            return false;
        

        if (busarea6 != null ? !busarea6.equals(that.busarea6) : that.busarea6 != null)
            return false;
        

        if (busareaabbr6 != null ? !busareaabbr6.equals(that.busareaabbr6) : that.busareaabbr6 != null)
            return false;
        

        if (busareadesc6 != null ? !busareadesc6.equals(that.busareadesc6) : that.busareadesc6 != null)
            return false;
        

        if (busarea7 != null ? !busarea7.equals(that.busarea7) : that.busarea7 != null)
            return false;
        

        if (busareaabbr7 != null ? !busareaabbr7.equals(that.busareaabbr7) : that.busareaabbr7 != null)
            return false;
        

        if (busareadesc7 != null ? !busareadesc7.equals(that.busareadesc7) : that.busareadesc7 != null)
            return false;
        

        if (busarea8 != null ? !busarea8.equals(that.busarea8) : that.busarea8 != null)
            return false;
        

        if (busareaabbr8 != null ? !busareaabbr8.equals(that.busareaabbr8) : that.busareaabbr8 != null)
            return false;
        

        if (busareadesc8 != null ? !busareadesc8.equals(that.busareadesc8) : that.busareadesc8 != null)
            return false;
        

        if (busarea9 != null ? !busarea9.equals(that.busarea9) : that.busarea9 != null)
            return false;
        

        if (busareaabbr9 != null ? !busareaabbr9.equals(that.busareaabbr9) : that.busareaabbr9 != null)
            return false;
        

        if (busareadesc9 != null ? !busareadesc9.equals(that.busareadesc9) : that.busareadesc9 != null)
            return false;
        

        if (busarea10 != null ? !busarea10.equals(that.busarea10) : that.busarea10 != null)
            return false;
        

        if (busareaabbr10 != null ? !busareaabbr10.equals(that.busareaabbr10) : that.busareaabbr10 != null)
            return false;
        

        if (busareadesc10 != null ? !busareadesc10.equals(that.busareadesc10) : that.busareadesc10 != null)
            return false;
        

        if (opnonopstatusreason != null ? !opnonopstatusreason.equals(that.opnonopstatusreason) : that.opnonopstatusreason != null)
            return false;
        

        if (opnonopstartdate != null ? !opnonopstartdate.equals(that.opnonopstartdate) : that.opnonopstartdate != null)
            return false;
        

        if (opnonopenddate != null ? !opnonopenddate.equals(that.opnonopenddate) : that.opnonopenddate != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = sevendigitstaffid != null ? sevendigitstaffid.hashCode() : 0;

        res = 31 * res + (forename != null ? forename.hashCode() : 0);

        res = 31 * res + (surname != null ? surname.hashCode() : 0);

        res = 31 * res + (sapcostcentrecompany != null ? sapcostcentrecompany.hashCode() : 0);

        res = 31 * res + (startdt != null ? startdt.hashCode() : 0);

        res = 31 * res + (enddt != null ? enddt.hashCode() : 0);

        res = 31 * res + (corporatetitle != null ? corporatetitle.hashCode() : 0);

        res = 31 * res + (globallevel != null ? globallevel.hashCode() : 0);

        res = 31 * res + (stafftype != null ? stafftype.hashCode() : 0);

        res = 31 * res + (staffsubtype != null ? staffsubtype.hashCode() : 0);

        res = 31 * res + (staffstatus != null ? staffstatus.hashCode() : 0);

        res = 31 * res + (staffclass != null ? staffclass.hashCode() : 0);

        res = 31 * res + (globalstaffid != null ? globalstaffid.hashCode() : 0);

        res = 31 * res + (taxnumber != null ? taxnumber.hashCode() : 0);

        res = 31 * res + (orgunit != null ? orgunit.hashCode() : 0);

        res = 31 * res + (orgunitabbv != null ? orgunitabbv.hashCode() : 0);

        res = 31 * res + (orgunitdesc != null ? orgunitdesc.hashCode() : 0);

        res = 31 * res + (dept != null ? dept.hashCode() : 0);

        res = 31 * res + (deptabbv != null ? deptabbv.hashCode() : 0);

        res = 31 * res + (deptdesc != null ? deptdesc.hashCode() : 0);

        res = 31 * res + (buildingdesc != null ? buildingdesc.hashCode() : 0);

        res = 31 * res + (countrydesc != null ? countrydesc.hashCode() : 0);

        res = 31 * res + (firstname != null ? firstname.hashCode() : 0);

        res = 31 * res + (jobkey != null ? jobkey.hashCode() : 0);

        res = 31 * res + (linemanagerid != null ? linemanagerid.hashCode() : 0);

        res = 31 * res + (previouslastname != null ? previouslastname.hashCode() : 0);

        res = 31 * res + (gender != null ? gender.hashCode() : 0);

        res = 31 * res + (lastdayworked != null ? lastdayworked.hashCode() : 0);

        res = 31 * res + (emailaddr != null ? emailaddr.hashCode() : 0);

        res = 31 * res + (previouscostcentre != null ? previouscostcentre.hashCode() : 0);

        res = 31 * res + (lastdaypaid != null ? lastdaypaid.hashCode() : 0);

        res = 31 * res + (dateofbirth != null ? dateofbirth.hashCode() : 0);

        res = 31 * res + (nationalitycode != null ? nationalitycode.hashCode() : 0);

        res = 31 * res + (maternitydatefrom != null ? maternitydatefrom.hashCode() : 0);

        res = 31 * res + (maternitydateto != null ? maternitydateto.hashCode() : 0);

        res = 31 * res + (absence != null ? absence.hashCode() : 0);

        res = 31 * res + (entitycode != null ? entitycode.hashCode() : 0);

        res = 31 * res + (entitytext != null ? entitytext.hashCode() : 0);

        res = 31 * res + (busarea1 != null ? busarea1.hashCode() : 0);

        res = 31 * res + (busareaabbr1 != null ? busareaabbr1.hashCode() : 0);

        res = 31 * res + (busareadesc1 != null ? busareadesc1.hashCode() : 0);

        res = 31 * res + (busarea2 != null ? busarea2.hashCode() : 0);

        res = 31 * res + (busareaabbr2 != null ? busareaabbr2.hashCode() : 0);

        res = 31 * res + (busareadesc2 != null ? busareadesc2.hashCode() : 0);

        res = 31 * res + (busarea3 != null ? busarea3.hashCode() : 0);

        res = 31 * res + (busareaabbr3 != null ? busareaabbr3.hashCode() : 0);

        res = 31 * res + (busareadesc3 != null ? busareadesc3.hashCode() : 0);

        res = 31 * res + (busarea4 != null ? busarea4.hashCode() : 0);

        res = 31 * res + (busareaabbr4 != null ? busareaabbr4.hashCode() : 0);

        res = 31 * res + (busareadesc4 != null ? busareadesc4.hashCode() : 0);

        res = 31 * res + (leavingcode != null ? leavingcode.hashCode() : 0);

        res = 31 * res + (graduatestartdate != null ? graduatestartdate.hashCode() : 0);

        res = 31 * res + (localhirerehire != null ? localhirerehire.hashCode() : 0);

        res = 31 * res + (localsupervisor != null ? localsupervisor.hashCode() : 0);

        res = 31 * res + (linemanagerbrid != null ? linemanagerbrid.hashCode() : 0);

        res = 31 * res + (brid != null ? brid.hashCode() : 0);

        res = 31 * res + (personnelarea != null ? personnelarea.hashCode() : 0);

        res = 31 * res + (personnelareadesc != null ? personnelareadesc.hashCode() : 0);

        res = 31 * res + (busarea5 != null ? busarea5.hashCode() : 0);

        res = 31 * res + (busareaabbr5 != null ? busareaabbr5.hashCode() : 0);

        res = 31 * res + (busareadesc5 != null ? busareadesc5.hashCode() : 0);

        res = 31 * res + (subfunction != null ? subfunction.hashCode() : 0);

        res = 31 * res + (subfunctiondesc != null ? subfunctiondesc.hashCode() : 0);

        res = 31 * res + (function != null ? function.hashCode() : 0);

        res = 31 * res + (functiondesc != null ? functiondesc.hashCode() : 0);

        res = 31 * res + (sapcostcentretext != null ? sapcostcentretext.hashCode() : 0);

        res = 31 * res + (companycode != null ? companycode.hashCode() : 0);

        res = 31 * res + (companycodetxt != null ? companycodetxt.hashCode() : 0);

        res = 31 * res + (operationalstatusind != null ? operationalstatusind.hashCode() : 0);

        res = 31 * res + (citizencard != null ? citizencard.hashCode() : 0);

        res = 31 * res + (evetelephoneno != null ? evetelephoneno.hashCode() : 0);

        res = 31 * res + (identificationcard != null ? identificationcard.hashCode() : 0);

        res = 31 * res + (pannumber != null ? pannumber.hashCode() : 0);

        res = 31 * res + (nationalidcardno != null ? nationalidcardno.hashCode() : 0);

        res = 31 * res + (labourcardnumberid != null ? labourcardnumberid.hashCode() : 0);

        res = 31 * res + (personalmobceltelephoneno != null ? personalmobceltelephoneno.hashCode() : 0);

        res = 31 * res + (employmentpass != null ? employmentpass.hashCode() : 0);

        res = 31 * res + (singaporeblue != null ? singaporeblue.hashCode() : 0);

        res = 31 * res + (passport != null ? passport.hashCode() : 0);

        res = 31 * res + (hongkongidentityno != null ? hongkongidentityno.hashCode() : 0);

        res = 31 * res + (uniquenationalid != null ? uniquenationalid.hashCode() : 0);

        res = 31 * res + (singaporepink != null ? singaporepink.hashCode() : 0);

        res = 31 * res + (visaworkpermitreftier2 != null ? visaworkpermitreftier2.hashCode() : 0);

        res = 31 * res + (busarea6 != null ? busarea6.hashCode() : 0);

        res = 31 * res + (busareaabbr6 != null ? busareaabbr6.hashCode() : 0);

        res = 31 * res + (busareadesc6 != null ? busareadesc6.hashCode() : 0);

        res = 31 * res + (busarea7 != null ? busarea7.hashCode() : 0);

        res = 31 * res + (busareaabbr7 != null ? busareaabbr7.hashCode() : 0);

        res = 31 * res + (busareadesc7 != null ? busareadesc7.hashCode() : 0);

        res = 31 * res + (busarea8 != null ? busarea8.hashCode() : 0);

        res = 31 * res + (busareaabbr8 != null ? busareaabbr8.hashCode() : 0);

        res = 31 * res + (busareadesc8 != null ? busareadesc8.hashCode() : 0);

        res = 31 * res + (busarea9 != null ? busarea9.hashCode() : 0);

        res = 31 * res + (busareaabbr9 != null ? busareaabbr9.hashCode() : 0);

        res = 31 * res + (busareadesc9 != null ? busareadesc9.hashCode() : 0);

        res = 31 * res + (busarea10 != null ? busarea10.hashCode() : 0);

        res = 31 * res + (busareaabbr10 != null ? busareaabbr10.hashCode() : 0);

        res = 31 * res + (busareadesc10 != null ? busareadesc10.hashCode() : 0);

        res = 31 * res + (opnonopstatusreason != null ? opnonopstatusreason.hashCode() : 0);

        res = 31 * res + (opnonopstartdate != null ? opnonopstartdate.hashCode() : 0);

        res = 31 * res + (opnonopenddate != null ? opnonopenddate.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "FeedSapEmployee [" + 
            "sevendigitstaffid=" + sevendigitstaffid + ", " + 
            "forename=" + forename + ", " + 
            "surname=" + surname + ", " + 
            "sapcostcentrecompany=" + sapcostcentrecompany + ", " + 
            "startdt=" + startdt + ", " + 
            "enddt=" + enddt + ", " + 
            "corporatetitle=" + corporatetitle + ", " + 
            "globallevel=" + globallevel + ", " + 
            "stafftype=" + stafftype + ", " + 
            "staffsubtype=" + staffsubtype + ", " + 
            "staffstatus=" + staffstatus + ", " + 
            "staffclass=" + staffclass + ", " + 
            "globalstaffid=" + globalstaffid + ", " + 
            "taxnumber=" + taxnumber + ", " + 
            "orgunit=" + orgunit + ", " + 
            "orgunitabbv=" + orgunitabbv + ", " + 
            "orgunitdesc=" + orgunitdesc + ", " + 
            "dept=" + dept + ", " + 
            "deptabbv=" + deptabbv + ", " + 
            "deptdesc=" + deptdesc + ", " + 
            "buildingdesc=" + buildingdesc + ", " + 
            "countrydesc=" + countrydesc + ", " + 
            "firstname=" + firstname + ", " + 
            "jobkey=" + jobkey + ", " + 
            "linemanagerid=" + linemanagerid + ", " + 
            "previouslastname=" + previouslastname + ", " + 
            "gender=" + gender + ", " + 
            "lastdayworked=" + lastdayworked + ", " + 
            "emailaddr=" + emailaddr + ", " + 
            "previouscostcentre=" + previouscostcentre + ", " + 
            "lastdaypaid=" + lastdaypaid + ", " + 
            "dateofbirth=" + dateofbirth + ", " + 
            "nationalitycode=" + nationalitycode + ", " + 
            "maternitydatefrom=" + maternitydatefrom + ", " + 
            "maternitydateto=" + maternitydateto + ", " + 
            "absence=" + absence + ", " + 
            "entitycode=" + entitycode + ", " + 
            "entitytext=" + entitytext + ", " + 
            "busarea1=" + busarea1 + ", " + 
            "busareaabbr1=" + busareaabbr1 + ", " + 
            "busareadesc1=" + busareadesc1 + ", " + 
            "busarea2=" + busarea2 + ", " + 
            "busareaabbr2=" + busareaabbr2 + ", " + 
            "busareadesc2=" + busareadesc2 + ", " + 
            "busarea3=" + busarea3 + ", " + 
            "busareaabbr3=" + busareaabbr3 + ", " + 
            "busareadesc3=" + busareadesc3 + ", " + 
            "busarea4=" + busarea4 + ", " + 
            "busareaabbr4=" + busareaabbr4 + ", " + 
            "busareadesc4=" + busareadesc4 + ", " + 
            "leavingcode=" + leavingcode + ", " + 
            "graduatestartdate=" + graduatestartdate + ", " + 
            "localhirerehire=" + localhirerehire + ", " + 
            "localsupervisor=" + localsupervisor + ", " + 
            "linemanagerbrid=" + linemanagerbrid + ", " + 
            "brid=" + brid + ", " + 
            "personnelarea=" + personnelarea + ", " + 
            "personnelareadesc=" + personnelareadesc + ", " + 
            "busarea5=" + busarea5 + ", " + 
            "busareaabbr5=" + busareaabbr5 + ", " + 
            "busareadesc5=" + busareadesc5 + ", " + 
            "subfunction=" + subfunction + ", " + 
            "subfunctiondesc=" + subfunctiondesc + ", " + 
            "function=" + function + ", " + 
            "functiondesc=" + functiondesc + ", " + 
            "sapcostcentretext=" + sapcostcentretext + ", " + 
            "companycode=" + companycode + ", " + 
            "companycodetxt=" + companycodetxt + ", " + 
            "operationalstatusind=" + operationalstatusind + ", " + 
            "citizencard=" + citizencard + ", " + 
            "evetelephoneno=" + evetelephoneno + ", " + 
            "identificationcard=" + identificationcard + ", " + 
            "pannumber=" + pannumber + ", " + 
            "nationalidcardno=" + nationalidcardno + ", " + 
            "labourcardnumberid=" + labourcardnumberid + ", " + 
            "personalmobceltelephoneno=" + personalmobceltelephoneno + ", " + 
            "employmentpass=" + employmentpass + ", " + 
            "singaporeblue=" + singaporeblue + ", " + 
            "passport=" + passport + ", " + 
            "hongkongidentityno=" + hongkongidentityno + ", " + 
            "uniquenationalid=" + uniquenationalid + ", " + 
            "singaporepink=" + singaporepink + ", " + 
            "visaworkpermitreftier2=" + visaworkpermitreftier2 + ", " + 
            "busarea6=" + busarea6 + ", " + 
            "busareaabbr6=" + busareaabbr6 + ", " + 
            "busareadesc6=" + busareadesc6 + ", " + 
            "busarea7=" + busarea7 + ", " + 
            "busareaabbr7=" + busareaabbr7 + ", " + 
            "busareadesc7=" + busareadesc7 + ", " + 
            "busarea8=" + busarea8 + ", " + 
            "busareaabbr8=" + busareaabbr8 + ", " + 
            "busareadesc8=" + busareadesc8 + ", " + 
            "busarea9=" + busarea9 + ", " + 
            "busareaabbr9=" + busareaabbr9 + ", " + 
            "busareadesc9=" + busareadesc9 + ", " + 
            "busarea10=" + busarea10 + ", " + 
            "busareaabbr10=" + busareaabbr10 + ", " + 
            "busareadesc10=" + busareadesc10 + ", " + 
            "opnonopstatusreason=" + opnonopstatusreason + ", " + 
            "opnonopstartdate=" + opnonopstartdate + ", " + 
            "opnonopenddate=" + opnonopenddate +
        "]";
    }
}