package load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (01/10/2019, 03:32) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start("hue-oracle-client.xml")) {
            System.out.println(">>> Loading caches...");

            System.out.println(">>> Loading cache: FeedSapEmployeeCache");
            ignite.cache("FeedSapEmployeeCache").loadCache(null);

            System.out.println(">>> All caches loaded!");
        }
    }
}