package startup;

import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (01/10/2019, 03:32) **/
public class ServerNodeSpringStartup {
    /**
     * Start up node with specified configuration.
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        Ignition.start("hue-oracle-server.xml");
    }
}